/*Intialize elements before creating a min heap*/
void init(char*c,int*f){
	int i;
	for(i=0;i<count;i++){
		node*temp=(node*)malloc(sizeof(node));
		temp->c=c[i];
		temp->f=f[i];
		temp->left=temp->right=NULL;
		h[i]=temp;
	}
}

/*Convert binary search tree to a min heap*/
void minheapify(){
	int i,j,k;
	node*key;

	for(k=1;k<count;k++){
		i=k;		
		key=h[i];
		j=(i-1)/2;

		while(h[j]->f>key->f&&i>0){
			h[i]=h[j];
			i=j;
			j=(i-1)/2;
		}
		h[i]=key;
	}
}

/*Adjust the position of new node added to maintain the min heap*/
void adjust(){
	int i=0;
	node*key=h[i];
	int j=2*i+1;

	while(j<count && h[j]->f<key->f){
		if(j<count)
			if(j+1<count)
				if(h[j+1]->f<h[j]->f)
					j++;
		h[i]=h[j];
		i=j;
		j=2*i+1;
	}
	h[i]=key;
}

/*Find 2 chracters with lowest frequency and create a parent node with their sum*/
void combine(){
	node*s1,*s2,*temp;
	int t=count;
	while(t>1){
		s1=h[0];
		h[0]=h[count-1];
		count--;
		adjust();

		s2=h[0];
		h[0]=h[count-1];
		count--;
		adjust();

		temp=(node*)malloc(sizeof(node));
		temp->c='$';
		temp->f=s1->f+s2->f;

		if(s1->f<s2->f){
			temp->left=s1;
			temp->right=s2;
		}
		else{
			temp->left=s2;
			temp->right=s1;
		}
		count++;
		h[count-1]=temp;
		minheapify(count);
		t--;
	}
}

// Print the Huffman codes for the unique characters found in the given text file
void printCodes(node*root,int*arr,int top){
	if(root->left){
		arr[top]=0;
		printCodes(root->left,arr,top+1);
	}
	if(root->right){
		arr[top]=1;
		printCodes(root->right,arr,top+1);
	}

	if(!root->left && !root->right){
		if(root->c=='\t')
			printf("tab :");
		else if(root->c=='\n')
			printf("newline :");
		else if(root->c==' ')
			printf("space :");
		else
			printf("%c :",root->c);
		int i;
		putc(root->c,hfcode);
		putc(' ',hfcode);
		for(i=0;i<top;i++){
			putc(arr[i]+48,hfcode);
			printf("%d",arr[i]);
		}
		printf("\n");
		putc('\n',hfcode);

		t+=i*root->f;
	}		
}

/*Decompress the compressed output file generated by using Huffman codes*/
int printChar(node*root,int*finalarr,int top){
	if(finalarr[top]==0 && top<z && root->left)
		printChar(root->left,finalarr,top+1);
	
	if(finalarr[top]==1 && top<z && root->right)
		printChar(root->right,finalarr,top+1);

	if(!root->left && !root->right){
		printf("%c",root->c);
		root=h[0];
		printChar(root,finalarr,top);
	}
	if(top==z)
		return 1;
}

